<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [

        [
    'name_ar' => 'تاك تات جرة كمون بودرة 150 جم',
    'name_en' => 'Tak Tat Cumin Powder Jar 150g',
    'description_ar' => 'جرة كمون بودرة تاك تات 150 جم – كمون مطحون نقي لتعزيز طعم الأطعمة المتنوعة.',
    'description_en' => 'Pure ground cumin to enhance the flavor of various dishes.',
    'selling_price' => 17.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تاكتات جرة بهارات مشكلة 150 جرام',
    'name_en' => 'Tak Tat Mixed Spices Jar 150g',
    'description_ar' => 'تاكتات جرة بهارات مشكلة 150 جرام',
    'description_en' => 'Mixed spices blend for everyday cooking.',
    'selling_price' => 17.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تاك تات حب الهيل 250 جم',
    'name_en' => 'Tak Tat Cardamom Pods 250g',
    'description_ar' => 'حب الهيل تاك تات 250 جم – حبوب هيل كاملة عالية الجودة لإضافة نكهة عطرية قوية للأطباق.',
    'description_en' => 'High-quality whole cardamom pods that add a strong aromatic flavor to dishes.',
    'selling_price' => 69.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => true,
],

[
    'name_ar' => 'تاكتات جرة حبة سوداء 150 جرام',
    'name_en' => 'Tak Tat Black Seed Jar 150g',
    'description_ar' => 'تاكتات جرة حبة سوداء 150 جرام',
    'description_en' => 'Black seeds (Nigella) for seasoning and traditional recipes.',
    'selling_price' => 15.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تاك تات جرة فلفل أسود 160 جم',
    'name_en' => 'Tak Tat Black Pepper Powder Jar 160g',
    'description_ar' => 'جرة فلفل أسود تاك تات 160 جم – فلفل أسود مطحون عالي الجودة لإضافة حرارة ونكهة مميزة.',
    'description_en' => 'High-quality ground black pepper to add heat and rich flavor.',
    'selling_price' => 19.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تاكتات جرة بودرة زنجبيل 150 جرام',
    'name_en' => 'Tak Tat Ginger Powder Jar 150g',
    'description_ar' => 'تاكتات جرة بودرة زنجبيل 150جرام',
    'description_en' => 'Ground ginger powder for cooking and baking.',
    'selling_price' => 16.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تاك تات ترمس حلو 700 جم',
    'name_en' => 'Tak Tat Sweet Lupin Beans 700g',
    'description_ar' => 'ترمس حلو تاك تات 700 جم – ترمس حلو عالي الجودة للوجبات الخفيفة والمقبلات.',
    'description_en' => 'High-quality sweet lupin beans for snacks and appetizers.',
    'selling_price' => 23.00 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات سميد ناعم كيس 700 جم',
    'name_en' => 'Tak Tat Fine Semolina 700g',
    'description_ar' => 'سميد ناعم للخبز والطهي.',
    'description_en' => 'Fine semolina for baking and cooking.',
    'selling_price' => 15.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات جوز هند مجفف 400 جم',
    'name_en' => 'Tak Tat Desiccated Coconut 400g',
    'description_ar' => 'جوز هند مجفف للخبز والحلويات.',
    'description_en' => 'Dried coconut for baking and desserts.',
    'selling_price' => 22.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات ليمون مجفف كيس 150 جم',
    'name_en' => 'Tak Tat Dried Lemon 150g',
    'description_ar' => 'ليمون مجفف للشوربات واليخنات وإضافة النكهة.',
    'description_en' => 'Dried lemon for soups, stews, and flavoring.',
    'selling_price' => 8.25 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات عدس أحمر زيرو 700 جم',
    'name_en' => 'Tak Tat Red Lentils Zero 700g',
    'description_ar' => 'عدس أحمر زيرو للشوربات واليخنات.',
    'description_en' => 'Red lentils ideal for soups and stews.',
    'selling_price' => 17.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات ورق غار 35 جم',
    'name_en' => 'Tak Tat Bay Leaves 35g',
    'description_ar' => 'ورق غار عطري للطهي والتتبيل.',
    'description_en' => 'Aromatic bay leaves for cooking and seasoning.',
    'selling_price' => 3.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],
[
    'name_ar' => 'تك تات عدس أحمر هندي 700 جم',
    'name_en' => 'Tak Tat Indian Red Lentils 700g',
    'description_ar' => 'عدس أحمر هندي للطهي.',
    'description_en' => 'Indian red lentils suitable for cooking.',
    'selling_price' => 17.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات برغل ناعم 700 جم',
    'name_en' => 'Tak Tat Fine Bulgur 700g',
    'description_ar' => 'برغل ناعم للسلطات والبلاوف.',
    'description_en' => 'Fine bulgur wheat for salads and pilaf dishes.',
    'selling_price' => 18.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات سميد كيس 700 جم',
    'name_en' => 'Tak Tat Semolina 700g',
    'description_ar' => 'سميد للخبز والحلويات.',
    'description_en' => 'Semolina suitable for baking and desserts.',
    'selling_price' => 15.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات سميد كيس 2 كجم',
    'name_en' => 'Tak Tat Semolina 2kg',
    'description_ar' => 'سميد للخبز والحلويات.',
    'description_en' => 'Semolina for baking and sweets.',
    'selling_price' => 17.45 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات عدس أسود كيس 700 جم',
    'name_en' => 'Tak Tat Black Lentils 700g',
    'description_ar' => 'عدس أسود للشوربات واليخنات والسلطات.',
    'description_en' => 'Black lentils for soups, stews, and salads.',
    'selling_price' => 17.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات برغل خشن أبيض 700 جم',
    'name_en' => 'Tak Tat Coarse White Bulgur 700g',
    'description_ar' => 'اختيار مثالي لوجبة خفيفة صحية ومغذية، بديل للأرز والمعكرونة، غني بالألياف والبروتين.',
    'description_en' => 'Ideal for a healthy and nutritious meal, a great alternative to rice and pasta, rich in fiber and protein.',
    'selling_price' => 18.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات مسحوق سماق كيس 150 جم',
    'name_en' => 'Tak Tat Sumac Powder 150g',
    'description_ar' => 'مسحوق السماق للتتبيل.',
    'description_en' => 'Ground sumac for seasoning.',
    'selling_price' => 3.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات بهارات شوربة 300 جم',
    'name_en' => 'Tak Tat Soup Spice Mix 300g',
    'description_ar' => 'بهارات شوربة مشكلة لإضافة النكهة للأطباق.',
    'description_en' => 'Mixed soup spices to enhance dish flavors.',
    'selling_price' => 8.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تاك تات سمسم أبيض 200 جم',
    'name_en' => 'Tak Tat White Sesame Seeds 200g',
    'description_ar' => 'بذور سمسم أبيض طازجة للطبخ والخبز.',
    'description_en' => 'Fresh white sesame seeds for cooking and baking.',
    'selling_price' => 8.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تاك تات حبوب فلفل أسود 140 جم',
    'name_en' => 'Tak Tat Black Peppercorns 140g',
    'description_ar' => 'حبوب فلفل أسود بطعم قوي وعطري.',
    'description_en' => 'Black peppercorns with strong and aromatic flavor.',
    'selling_price' => 13.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات دقيق الأرز 700 جم',
    'name_en' => 'Tak Tat Rice Flour 700g',
    'description_ar' => 'دقيق أرز للطهي والخبز.',
    'description_en' => 'Rice flour for cooking and baking.',
    'selling_price' => 14.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات بذور قرنفل 100 جم',
    'name_en' => 'Tak Tat Clove Seeds 100g',
    'description_ar' => 'بذور قرنفل لتتبيل الأطباق والمشروبات.',
    'description_en' => 'Cloves for seasoning dishes and beverages.',
    'selling_price' => 14.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات عدس أحمر هندي 2 كجم',
    'name_en' => 'Tak Tat Indian Red Lentils 2kg',
    'description_ar' => 'عدس أحمر هندي للشوربات واليخنات.',
    'description_en' => 'Indian red lentils for soups and stews.',
    'selling_price' => 17.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات بذور كزبرة 150 جم',
    'name_en' => 'Tak Tat Coriander Seeds 150g',
    'description_ar' => 'بذور كزبرة للطهي.',
    'description_en' => 'Coriander seeds for cooking.',
    'selling_price' => 6.75 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات جوز هند مجفف 1 كجم',
    'name_en' => 'Tak Tat Desiccated Coconut 1kg',
    'description_ar' => 'جوز هند مجفف للخبز والحلويات.',
    'description_en' => 'Dried coconut for baking and desserts.',
    'selling_price' => 43.50 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات بذور فلفل أسود 100 جم',
    'name_en' => 'Tak Tat Black Pepper Seeds 100g',
    'description_ar' => 'بذور فلفل أسود للتتبيل.',
    'description_en' => 'Black pepper seeds for seasoning.',
    'selling_price' => 11.25 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تاك تات حبوب كمون 150 جم',
    'name_en' => 'Tak Tat Cumin Seeds 150g',
    'description_ar' => 'حبوب الكمون الكاملة لإضافة نكهة أصيلة لأطباقك.',
    'description_en' => 'Whole cumin seeds to add authentic flavor to your dishes.',
    'selling_price' => 13.5 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات بذور كمون 100 جم',
    'name_en' => 'Tak Tat Cumin Seeds 100g',
    'description_ar' => 'بذور كمون للتتبيل.',
    'description_en' => 'Cumin seeds for seasoning.',
    'selling_price' => 8.99 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

[
    'name_ar' => 'تك تات سمك مجفف 150 جم',
    'name_en' => 'Tak Tat Dried Fish 150g',
    'description_ar' => 'سمك مجفف تقليدي لإضافة نكهة للأطباق.',
    'description_en' => 'Traditional dried fish used to enhance dish flavors.',
    'selling_price' => 9.75 / 3.75,
    'minimum_alert_quantity' => 5,
    'category_id' => 8,
    'company_id' => 22,
    'featured' => false,
],

            // [
            //     'name_ar' => 'المطاحن الأولى طحين مخابز 10 كجم',
            //     'name_en' => 'First Mills Bakery Flour 10kg',
            //     'description_ar' => 'المطاحن الأولى طحين مخابز 10 كجم هو طحين عالي الجودة مخصص للمخابز وصنع المعجنات والخبز.',
            //     'description_en' => 'High-quality bakery flour specially made for bakeries, pastries, and bread making.',
            //     'selling_price' => 4.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 3,
            //     'company_id' => 17,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'بيلزبيري خليط كيك فانيلا 360 جم',
            //     'name_en' => 'Pillsbury Vanilla Cake Mix 360g',
            //     'description_ar' => 'بيلزبيري خليط كيك فانيلا 360 جم هو خليط كيك فانيلا جاهز يوفر طعمًا ناعمًا ولذيذًا.',
            //     'description_en' => 'Ready vanilla cake mix that delivers a smooth and delicious taste.',
            //     'selling_price' => 7 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 3,
            //     'company_id' => 19,
            //     'featured' => true,
            // ],

            // [
            //     'name_ar' => 'فينه طحين المخبوزات 10 كجم',
            //     'name_en' => 'Finah Bakery Flour 10kg',
            //     'description_ar' => 'فينه طحين المخبوزات 10 كجم هو طحين مخصص للمخبوزات يوفر جودة ممتازة للعجين.',
            //     'description_en' => 'Bakery flour designed for baked goods, providing excellent dough quality.',
            //     'selling_price' => 14.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 3,
            //     'company_id' => 20,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'بيتي كروكر خليط بان كيك بتر ميلك 907 جم',
            //     'name_en' => 'Betty Crocker Buttermilk Pancake Mix 907g',
            //     'description_ar' => 'خليط بان كيك بتر ميلك هش ولذيذ.',
            //     'description_en' => 'Fluffy and delicious buttermilk pancake mix.',
            //     'selling_price' => 23.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 3,
            //     'company_id' => 21,
            //     'featured' => true,
            // ],

            // [
            //     'name_ar' => 'بيتي كروكر خليك بانكيك 360جم',
            //     'name_en' => 'Betty Crocker Pancake Mix 360g',
            //     'description_ar' => 'كلاسيكي لإفطار هش ولذيذ.',
            //     'description_en' => 'Classic mix for a fluffy and tasty breakfast.',
            //     'selling_price' => 16.50 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 3,
            //     'company_id' => 21,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'بي سي خليط بان كيك حبوب كاملة 500 جم',
            //     'name_en' => 'BC Whole Wheat Pancake Mix 500g',
            //     'description_ar' => 'خليط بان كيك من الحبوب الكاملة لفطور صحي ومغذي.',
            //     'description_en' => 'Whole wheat pancake mix for a healthy and nutritious breakfast.',
            //     'selling_price' => 26.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 3,
            //     'company_id' => 18,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'ياماما دبس رمان 750 مل',
            //     'name_en' => 'Yamama Pomegranate Molasses 750ml',
            //     'description_ar' => 'ياماما دبس رمان 750 مل هو دبس رمان مركز بطعم غني، مثالي للمقبلات والطبخ.',
            //     'description_en' => 'Concentrated pomegranate molasses with a rich flavor, ideal for appetizers and cooking.',
            //     'selling_price' => 22.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'الضيافة مخلل ليمون 200جم',
            //     'name_en' => 'Aldiafa Pickled Lemon 200g',
            //     'description_ar' => 'الضيافة مخلل ليمون 200جم',
            //     'description_en' => 'Pickled lemon, perfect for traditional dishes.',
            //     'selling_price' => 13 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'ماجي ماجيك سراب 96جم',
            //     'name_en' => 'Maggi Magic Sarap Seasoning 96g',
            //     'description_ar' => 'ماجي ماجيك سراب 96جم',
            //     'description_en' => 'All-purpose seasoning mix to enhance flavor in various dishes.',
            //     'selling_price' => 9.50 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'فريشلي حليب جوز الهند 400 مل',
            //     'name_en' => 'Freshly Coconut Milk 400ml',
            //     'description_ar' => 'حليب جوز الهند للطهي والحلويات.',
            //     'description_en' => 'Coconut milk for cooking and desserts.',
            //     'selling_price' => 6.25 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'مكاتي صلصة حارة 280 مل',
            //     'name_en' => 'Makati Hot Sauce 280ml',
            //     'description_ar' => 'صلصة حارة 280 مل، صلصة حلوة وحارة معتدلة لإضافة طعم مميز لمختلف الأطباق.',
            //     'description_en' => 'Sweet and moderately spicy hot sauce to add a special flavor to various dishes.',
            //     'selling_price' => 7.75 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'ماجي معجون طبخ بالذرة والثوم 200 جم',
            //     'name_en' => 'Maggi Corn & Garlic Cooking Paste 200g',
            //     'description_ar' => 'معجون طبخ بالذرة والثوم لإضافة نكهة لذيذة للأطباق.',
            //     'description_en' => 'Corn and garlic cooking paste to add delicious flavor to dishes.',
            //     'selling_price' => 16.50 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'فرشلي لب تمر هندي 200 جرام',
            //     'name_en' => 'Freshly Tamarind Pulp 200g',
            //     'description_ar' => 'لب تمر هندي غني وحامض من فرشلي، مثالي للصلصات والتتبيلات والوصفات التقليدية.',
            //     'description_en' => 'Rich and tangy tamarind pulp, ideal for sauces, marinades, and traditional recipes.',
            //     'selling_price' => 11.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'مهران معجون زنجبيل وثوم 750 جم',
            //     'name_en' => 'Mehran Ginger & Garlic Paste 750g',
            //     'description_ar' => 'معجون زنجبيل وثوم جاهز للطبخ.',
            //     'description_en' => 'Ready-to-use ginger and garlic paste for cooking.',
            //     'selling_price' => 21.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => true,
            // ],

            // [
            //     'name_ar' => 'إيستيون تمر هندي 200 جم',
            //     'name_en' => 'Eastion Tamarind 200g',
            //     'description_ar' => 'تمر هندي طبيعي من إيستيون 200 جم لإعداد العصائر والأطباق الشرقية.',
            //     'description_en' => 'Natural tamarind for preparing juices and oriental dishes.',
            //     'selling_price' => 7.75 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'مهران معجون ثوم وزنجبيل 320 جم',
            //     'name_en' => 'Mehran Garlic & Ginger Paste 320g',
            //     'description_ar' => 'معجون ثوم وزنجبيل جاهز للاستخدام. يضيف نكهة قوية ورائحة مميزة للطبخ.',
            //     'description_en' => 'Ready-to-use garlic and ginger paste that adds strong flavor and aroma to cooking.',
            //     'selling_price' => 6.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'فريشلي فلفل جالابينو شرائح 510 جم',
            //     'name_en' => 'Freshly Sliced Jalapeno Peppers 510g',
            //     'description_ar' => 'شرائح فلفل جالابينو في محلول ملحي.',
            //     'description_en' => 'Sliced jalapeno peppers in brine.',
            //     'selling_price' => 16.50 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'صُرة معجون فلفل 700 جم',
            //     'name_en' => 'Sorrah Pepper Paste 700g',
            //     'description_ar' => 'معجون الفلفل Sorrah Pepper Paste 700G، منتج غني بالنكهة الحارة، مثالي للطهي وإضافة طعم مميز للأطباق.',
            //     'description_en' => 'Rich and spicy pepper paste, ideal for cooking and enhancing flavors.',
            //     'selling_price' => 31.50 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => true,
            // ],

            // [
            //     'name_ar' => 'مكاتي حليب جوز الهند 165مل',
            //     'name_en' => 'Makati Coconut Milk 165ml',
            //     'description_ar' => 'حليب جوز الهند من مكاتي 165 مل، ناعم وطبيعي، مثالي للطهي والحلويات.',
            //     'description_en' => 'Smooth and natural coconut milk, ideal for cooking and desserts.',
            //     'selling_price' => 4.25 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'إيستيون حليب جوز الهند 400 جم',
            //     'name_en' => 'Eastion Coconut Milk 400ml',
            //     'description_ar' => 'حليب جوز الهند من إيستيون 400 مل، كريمي وطبيعي، مناسب للطهي والشراب.',
            //     'description_en' => 'Creamy and natural coconut milk, suitable for cooking and beverages.',
            //     'selling_price' => 10.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'كروبوك جمبري أندونيسي 500 جم',
            //     'name_en' => 'Indonesian Shrimp Crackers 500g',
            //     'description_ar' => 'كروبوك جمبري أندونيسي 500 جم، رقائق قريدس مقرمشة جاهزة للتحضير أو كوجبة خفيفة.',
            //     'description_en' => 'Crunchy Indonesian shrimp crackers, ready to prepare or enjoy as a snack.',
            //     'selling_price' => 23.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => true,
            // ],

            // [
            //     'name_ar' => 'مكاتي مسحوق حليب جوز الهند 50 جم',
            //     'name_en' => 'Makati Coconut Milk Powder 50g',
            //     'description_ar' => 'مسحوق حليب جوز الهند الفوري 50 جم – مسحوق جوز الهند الفوري لإعداد المشروبات والحلويات بسهولة.',
            //     'description_en' => 'Instant coconut milk powder for preparing drinks and desserts easily.',
            //     'selling_price' => 5.50 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'ألفية رقاقات ثوم 227 جم',
            //     'name_en' => 'Alfeya Garlic Chips 227g',
            //     'description_ar' => 'رقائق الثوم من ألفية مقرمشة وذات نكهة غنية، مثالية للتقديم كوجبة خفيفة أو مع السلطات والمقبلات.',
            //     'description_en' => 'Crunchy garlic chips with rich flavor, perfect as a snack or with salads and appetizers.',
            //     'selling_price' => 7.25 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'مكاتي صلصة سمك المحار 300 مل',
            //     'name_en' => 'Makati Oyster Sauce 300ml',
            //     'description_ar' => 'صلصة سمك المحار 300 مل، صلصة غنية بنكهة المحار لتعزيز مذاق الأطعمة الآسيوية.',
            //     'description_en' => 'Rich oyster-flavored sauce to enhance the taste of Asian dishes.',
            //     'selling_price' => 12.50 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 2,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'تاندي مخلل شرائح خيار 680جم',
            //     'name_en' => 'Tandi Pickled Cucumber Slices 680g',
            //     'description_ar' => null,
            //     'description_en' => 'Pickled cucumber slices, crunchy and perfect for daily meals.',
            //     'selling_price' => 12.50 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'زيتون أسود كامل الجوف 1 كجم',
            //     'name_en' => 'Al-Jouf Whole Black Olives 1kg',
            //     'description_ar' => 'زيتون الجوف العضوي – طازج ومختار بعناية من مزارعنا في السعودية، بنكهة طبيعية وجودة عالية',
            //     'description_en' => 'Organic Al-Jouf olives – freshly and carefully selected from our farms in Saudi Arabia, with natural flavor and high quality.',
            //     'selling_price' => 21.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => true,
            // ],

            // [
            //     'name_ar' => 'زيتون أسود شرائح الجوف 1 كجم',
            //     'name_en' => 'Al-Jouf Sliced Black Olives 1kg',
            //     'description_ar' => 'زيتون الجوف العضوي – طازج ومختار بعناية من مزارعنا في السعودية، بنكهة طبيعية وجودة عالية',
            //     'description_en' => 'Organic Al-Jouf olives – freshly and carefully selected from our farms in Saudi Arabia, with natural flavor and high quality.',
            //     'selling_price' => 20.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'بيدر خيار مخلل 660 جم',
            //     'name_en' => 'Bader Pickled Cucumbers 660g',
            //     'description_ar' => 'خيار مخلل من بيدر 660 جم مقرمش ومنعش، مثالي للمقبلات والوجبات اليومية.',
            //     'description_en' => 'Crunchy and refreshing pickled cucumbers from Bader, perfect for appetizers and daily meals.',
            //     'selling_price' => 12.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'أليسا شرائح زيتون أسود 120 جم',
            //     'name_en' => 'Alyssa Sliced Black Olives 120g',
            //     'description_ar' => 'شرائح زيتون أسود جاهزة للاستخدام، مثالية للسلطات والبيتزا والسندويتشات.',
            //     'description_en' => 'Ready-to-use black olive slices, ideal for salads, pizza, and sandwiches.',
            //     'selling_price' => 11.5 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'كوبوليفا زيتون أسود منزوع النواة 75 جم',
            //     'name_en' => 'Copolive Pitted Black Olives 75g',
            //     'description_ar' => 'زيتون أسود منزوع النواة، نكهة غنية وطبيعية، مناسب للتقديم المباشر أو للطهي.',
            //     'description_en' => 'Pitted black olives with rich natural flavor, suitable for direct serving or cooking.',
            //     'selling_price' => 8.25 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'بندة زيتون أسود منزوع النواة 350 جرام',
            //     'name_en' => 'Panda Pitted Black Olives 350g',
            //     'description_ar' => null,
            //     'description_en' => 'Pitted black olives, perfect for meals and salads.',
            //     'selling_price' => 8.25 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'كوبوليفا زيتون أسود شرائح 510 جم',
            //     'name_en' => 'Copolive Sliced Black Olives 510g',
            //     'description_ar' => 'زيتون أسود كوبوليفا شرائح 510 جم، كمية أكبر من شرائح الزيتون الأسود للعائلات أو المطاعم.',
            //     'description_en' => 'Copolive sliced black olives 510g, larger quantity suitable for families or restaurants.',
            //     'selling_price' => 30.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => true,
            // ],

            // [
            //     'name_ar' => 'بندة زيتون أسود شرائح 700 جرام',
            //     'name_en' => 'Panda Sliced Black Olives 700g',
            //     'description_ar' => null,
            //     'description_en' => 'Sliced black olives, ideal for cooking and salads.',
            //     'selling_price' => 13.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => false,
            // ],

            // [
            //     'name_ar' => 'كوبوليفا زيتون أسود شرائح 360 جم',
            //     'name_en' => 'Copolive Sliced Black Olives 360g',
            //     'description_ar' => 'زيتون أسود كوبوليفا شرائح 360 جم، شرائح زيتون جاهزة للاستخدام في السلطات والأطباق.',
            //     'description_en' => 'Copolive sliced black olives 360g, ready-to-use olive slices for salads and dishes.',
            //     'selling_price' => 25.99 / 3.75,
            //     'minimum_alert_quantity' => 5,
            //     'category_id' => 1,
            //     'featured' => false,
            // ],

        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
